name: MLOPs with Databricks

on:
  push:
    branches:
      - 'main'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

jobs:
  setup-validate:
    name: Set Up Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GIT_BRANCH }}

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install UV
        uses: astral-sh/setup-uv@v5

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main
        with:
          version: 0.221.1

      - name: Deploy to Databricks
        env:
          DATABRICKS_BUNDLE_ENV: dev # bundle target
        run: databricks bundle deploy --var="git_sha=${{ github.sha }}"